---
- name: Loops Playbook
  hosts: all
  become: yes

 
		 
  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
	 register: output
	 delay: 2
	 retries: 10
	 until: output.stdout.find{"ZZZZ"} == false
	
  - name: Print output
    debug:
	   var: output.stdout
